
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
     - "2181:2181"
  kafka:
    depends_on: 
     - zookeeper
    image: wurstmeister/kafka
    ports:
     - "9092:9092"
     - '29094:29094'
    expose:
     - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,GBY://34.136.146.75:29094
      #KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,GBY://localhost:29094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,GBY:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,GBY://0.0.0.0:29094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "topic_test:1:1"
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
  scrapper:
      depends_on: 
      - kafka
      build: ./scrapper
      ports:
      - "7000:7000"
      command:
        - "python"
        - "-u"
        - "./tsla_crawl.py"
        - "kafka:9093"
        - "300"

